import moment from "moment/moment";
import book1 from "./Assets/bookImage1.avif";
import book2 from "./Assets/bookImage2.jpg";
import book3 from "./Assets/bookImage3.jpg";

export const sampleData = [
  {
    id: 111,
    name: "Console Wars",
    title: "Console Wars: Sega, Nintendo, and the Battle that Defined a Generation",
    author: "Harris J. Blake",
    price: 499,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/51zpf17Eh1L._SX330_BO1,204,203,200_.jpg",
    release_date: moment().subtract(5, "d").format(),
    reviews: [
      {
        id: 1126,
        user: "john Doe",
        rating: 4,
        comment:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas sed molestiae culpa, modi minus impedit. Alias praesentium fuga molestias quis?",
      },
      {
        id: 1127,
        user: "Unknown",
        rating: 2,
        comment:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique sed eligendi ex, quos voluptate facere soluta dolorem officiis nobis necessitatibus cupiditate iure nisi, sapiente quo neque sint est doloremque consequuntur.",
      },
      {
        id: 1128,
        user: "jasmine",
        rating: 4,
        comment: "Nice book",
      },
      {
        id: 1129,
        user: "kent_dodds",
        rating: 5,
        comment:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, sunt minima officia molestias ipsa quisquam?",
      },
      {
        id: 1130,
        user: "kent_dodds",
        rating: 3,
        comment:
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, sunt minima officia molestias ipsa quisquam?",
      },
    ],
    description:
      "Following the success of The Accidental Billionaires and Moneyball comes Console Wars a mesmerizing, behind-the-scenes business thriller that chronicles how Sega, a small, scrappy gaming company led by an unlikely visionary and a team of rebels, took on the juggernaut Nintendo and revolutionized the video game industry. In 1990, Nintendo had a virtual monopoly on the video game industry. Sega, on the other hand, was just a faltering arcade company with big aspirations and even bigger personalities. But that would all change with the arrival of Tom Kalinske, a man who knew nothing about videogames and everything about fighting uphill battles. His unconventional tactics, combined with the blood, sweat and bold ideas of his renegade employees, transformed Sega and eventually led to a ruthless David-and-Goliath showdown with rival Nintendo. The battle was vicious, relentless, and highly profitable, eventually sparking a global corporate war that would be fought on several fronts: from living rooms and schoolyards to boardrooms and Congress. It was a once-in-a-lifetime, no-holds-barred conflict that pitted brother against brother, kid against adult, Sonic against Mario, and the US against Japan. Based on over two hundred interviews with former Sega and Nintendo employees, Console Wars is the underdog tale of how Kalinske miraculously turned an industry punchline into a market leader. Its the story of how a humble family man, with an extraordinary imagination and a gift for turning problems into competitive advantages, inspired a team of underdogs to slay a giant and, as a result, birth a $60 billion dollar industry.",
  },
  {
    id: 112,
    name: "Book 2",
    title: "Sample Book 2",
    author: "Author 2",
    price: 599,
    image: book1,
    release_date: moment().subtract(10, "d").format(),
    reviews: [
      {
        id: 1124,
        user: "User 1",
        rating: 4,
        comment: "A great read!",
      },
      {
        id: 1125,
        user: "User 2",
        rating: 5,
        comment: "Couldn't put it down!",
      },
    ],
    description: "This is a sample book description for Book 2.",
  },
  {
    id: 113,
    name: "Book 3",
    title: "Sample Book 3",
    author: "Author 3",
    price: 999,
    image: book2,
    release_date: moment().subtract(20, "d").format(),
    reviews: [
      {
        id: 1123,
        user: "User 3",
        rating: 3,
        comment: "Decent book.",
      },
    ],
    description: "Another sample book description for Book 3.",
  },
  {
    id: 114,
    name: "Book 4",
    title: "Sample Book 4",
    author: "Author 4",
    price: 299,
    image: book3,
    release_date: moment().subtract(5, "d").format(),
    reviews: [
      {
        id: 1121,
        user: "User 4",
        rating: 5,
        comment: "Loved it!",
      },
      {
        id: 1122,
        user: "User 5",
        rating: 4,
        comment: "A must-read.",
      },
    ],
    description: "Sample book description for Book 4.",
  },
  {
    id: 115,
    name: "Book 5",
    title: "Sample Book 5",
    author: "Author 5",
    price: 449,
    image: book1,
    release_date: moment().subtract(15, "d").format(),
    reviews: [],
    description: "Yet another sample book description for Book 5.",
  },
  {
    id: 116,
    name: "Book 6",
    title: "Sample Book 6",
    author: "Author 6",
    price: 199,
    image: book2,
    release_date: moment().subtract(5, "d").format(),
    reviews: [
      {
        id: 1120,
        user: "User 6",
        rating: 4,
        comment: "Enjoyed every page!",
      },
    ],
    description: "Sample book description for Book 6.",
  },
  {
    id: 117,
    name: "Book 7",
    title: "Sample Book 7",
    author: "Author 7",
    price: 549,
    image: book2,
    release_date: moment().subtract(10, "d").format(),
    reviews: [],
    description: "Another sample book description for Book 7.",
  },
  {
    id: 159,
    name: "Book 8",
    title: "Sample Book 8",
    author: "Author 8",
    price: 600,
    image: book3,
    release_date: moment().subtract(25, "d").format(),
    reviews: [
      {
        id: 1119,
        user: "User 8",
        rating: 3,
        comment: "It was okay.",
      },
    ],
    description: "Sample book description for Book 8.",
  },
  {
    id: 199,
    name: "Book 9",
    title: "Sample Book 9",
    author: "Author 9",
    price: 799,
    image: book1,
    release_date: moment().subtract(5, "d").format(),
    reviews: [],
    description: "Yet another sample book description for Book 9.",
  },
  {
    id: 110,
    name: "Book 10",
    title: "Sample Book 10",
    author: "Author 10",
    price: 649,
    image: book2,
    release_date: moment().subtract(10, "d").format(),
    reviews: [
      {
        id: 1118,
        user: "User 10",
        rating: 5,
        comment: "A masterpiece!",
      },
    ],
    description: "This is a sample book description for Book 10.",
  },
  {
    id: 1111,
    name: "Book 11",
    title: "Sample Book 11",
    author: "Author 11",
    price: 499,
    image: book2,
    release_date: moment().subtract(5, "d").format(),
    reviews: [],
    description: "Sample book description for Book 11.",
  },
  {
    id: 1112,
    name: "Book 12",
    title: "Sample Book 12",
    author: "Author 12",
    price: 449,
    image: book3,
    release_date: moment().subtract(12, "d").format(),
    reviews: [
      {
        id: 1117,
        user: "User 12",
        rating: 4,
        comment: "A compelling read!",
      },
    ],
    description: "Another sample book description for Book 12.",
  },
  {
    id: 1113,
    name: "Book 13",
    title: "Sample Book 13",
    author: "Author 1",
    price: 999,
    image: book1,
    release_date: moment().subtract(8, "d").format(),
    reviews: [],
    description: "Yet another sample book description for Book 13.",
  },
  {
    id: 1114,
    name: "Book 14",
    title: "Sample Book 14",
    author: "Author 2",
    price: 749,
    image: book1,
    release_date: moment().subtract(5, "d").format(),
    reviews: [
      {
        id: 1116,
        user: "User 14",
        rating: 5,
        comment: "An excellent book!",
      },
      {
        id: 1117,
        user: "User 15",
        rating: 4,
        comment: "Highly recommended.",
      },
    ],
    description: "Sample book description for Book 14.",
  },
  {
    id: 139,
    name: "Book 15",
    title: "Sample Book 15",
    author: "Author 3",
    price: 499,
    image: book2,
    release_date: moment().subtract(18, "d").format(),
    reviews: [
      {
        id: 1115,
        user: "User 16",
        rating: 3,
        comment: "It was decent.",
      },
    ],
    description: "Another sample book description for Book 15.",
  },
  {
    id: 1116,
    name: "Book 16",
    title: "Sample Book 16",
    author: "Author 4",
    price: 199,
    image: book2,
    release_date: moment().subtract(5, "d").format(),
    reviews: [],
    description: "Sample book description for Book 16.",
  },
  {
    id: 187,
    name: "Book 17",
    title: "Sample Book 17",
    author: "Author 5",
    price: 399,
    image: book3,
    release_date: moment().subtract(14, "d").format(),
    reviews: [
      {
        id: 1114,
        user: "User 17",
        rating: 4,
        comment: "A captivating story!",
      },
    ],
    description: "Yet another sample book description for Book 17.",
  },
  {
    id: 118,
    name: "Book 18",
    title: "Sample Book 18",
    author: "Author 6",
    price: 349,
    image: book1,
    release_date: moment().subtract(11, "d").format(),
    reviews: [],
    description: "This is a sample book description for Book 18.",
  },
  {
    id: 119,
    name: "Book 19",
    title: "Sample Book 19",
    author: "Author 7",
    price: 349,
    image: book2,
    release_date: moment().subtract(5, "d").format(),
    reviews: [],
    description: "Another sample book description for Book 19.",
  },
  {
    id: 120,
    name: "Book 20",
    title: "Sample Book 20",
    author: "Author 13",
    price: 199,
    image: book3,
    release_date: moment().subtract(22, "d").format(),
    reviews: [],
    description: "Sample book description for Book 20.",
  },
  {
    id: 121,
    name: "Book 21",
    title: "Sample Book 21",
    author: "Author 8",
    price: 399,
    image: book1,
    release_date: moment().subtract(5, "d").format(),
    reviews: [
      {
        id: 1113,
        user: "User 21",
        rating: 5,
        comment: "Absolutely brilliant!",
      },
    ],
    description: "Yet another sample book description for Book 21.",
  },
  {
    id: 122,
    name: "Book 22",
    title: "Sample Book 22",
    author: "Author 9",
    price: 349,
    image: book2,
    release_date: moment().subtract(10, "d").format(),
    reviews: [
      {
        id: 1112,
        user: "User 22",
        rating: 4,
        comment: "A must-read.",
      },
    ],
    description: "This is a sample book description for Book 22.",
  },
  {
    id: 123,
    name: "Book 23",
    title: "Sample Book 23",
    author: "Author 10",
    price: 749,
    image: book3,
    release_date: moment().subtract(5, "d").format(),
    reviews: [],
    description: "Another sample book description for Book 23.",
  },
  {
    id: 124,
    name: "Book 24",
    title: "Sample Book 24",
    author: "Author 11",
    price: 599,
    image: book1,
    release_date: moment().subtract(16, "d").format(),
    reviews: [
      {
        id: 1111,
        user: "User 24",
        rating: 3,
        comment: "It was okay.",
      },
    ],
    description: "Sample book description for Book 24.",
  },
  {
    id: 125,
    name: "Book 25",
    title: "Sample Book 25",
    author: "Author 12",
    price: 699,
    image: book2,
    release_date: moment().subtract(5, "d").format(),
    reviews: [],
    description: "Yet another sample book description for Book 25.",
  },
];
